version: '3.9'

services:
  mariadb:
    image: mariadb:11
    container_name: spring-db
    restart: always
    # ports:
    #   - "3307:3306"  # 로컬 호스트 3307 → 컨테이너 3306 포트 매핑
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE:   # 데이터베이스명
      MYSQL_USER:   # 데이터베이스 유저명
      MYSQL_PASSWORD: # 데이터베이스 비밀번호
    command: --max-connections=1000
    networks:
      - spring-network

  backend:
    container_name: spring-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    env_file:
    - ./backend/.env 
    environment:
      - CONTAINER_TIMEZONE=Asia/Seoul
      - MYSQL_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER= # 데이터베이스 유저명
      - MYSQL_PASSWORD= # 데이터베이스 비밀번호
      - MYSQL_DATABASE= # 데이터베이스 명
    volumes:
      - ./backend:/app
    networks:
      - spring-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: spring-front
    restart: always
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL= # BACKEND_KAKAO_URI
    networks:
      - spring-network

 
volumes:
  mariadb_data:

networks:
  spring-network: