version: '3.9'

services:
  db:
      image: mariadb:11
      container_name: spring-db
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: dish_db
        MYSQL_USER: dish_user
        MYSQL_PASSWORD: dishpass
      volumes:
        - mariadb_data:/var/lib/mysql

  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: spring-backend
      restart: always
      ports:
        - "8000:8000"
      # depends_on:
      #   - db
      # environment:
      #   - DATABASE_URL=mysql+pymysql://dish_user:dishpass@db:3306/dish_db
      volumes:
        - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: spring-front
    restart: always
    ports:
      - "3000:3000"

volumes:
  mariadb_data:
networks:
  spring-network: